#!/bin/bash

commit_msg_file=$1

# Lê a mensagem do commit
commit_msg=$(cat "$commit_msg_file")

# Verifica se a mensagem do commit está no formato convencional
if ! grep -qE "^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+" "$commit_msg_file"; then
  echo "O formato da mensagem do commit é inválido. Use o formato convencional."
  exit 1
fi